package buscamascotas.IU;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import buscamascotas.sqliteconection.Operaciones.Operaciones;

/**
 *
 * @author Alberto
 */
public class BuscarAnimal extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9197623487553085929L;
	Operaciones consult = new Operaciones();
	private String sql;
	private String apellido1, dni;
	Object[] objetos;

	public Object[] getObjetos() {
		return objetos;
	}

	public void setObjetos(int i, Object dato) {
		this.objetos[i] = dato;
	}

	public String getDNI() {
		return dni;
	}

	public void setDNI(String dni) {
		this.dni = dni;
	}

	public String getApellido1() {
		return apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	public String getSql() {
		return sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}

	/**
	 * Creates new form Buscar
	 */
	public BuscarAnimal() {
		initComponents();

		salir();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings({ "unchecked", "serial" })
	private void initComponents() {

		apellidosText = new javax.swing.JTextField();
		nombreText = new javax.swing.JTextField();
		nombreLabel = new javax.swing.JLabel();
		apellidosLabel = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		animalesTable = new javax.swing.JTable();
		nombreLabel1 = new javax.swing.JLabel();
		nombreText1 = new javax.swing.JTextField();
		buscarAnimales = new javax.swing.JButton();
		volverButton1 = new javax.swing.JButton();
		salirButton1 = new javax.swing.JButton();
		razaText = new javax.swing.JTextField();
		razaLabel = new javax.swing.JLabel();
		fichaClienteButton = new javax.swing.JButton();
		fichaAnimalButton = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		apellidosText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				apellidosTextActionPerformed(evt);
			}
		});

		nombreLabel.setText("NOMBRE");

		apellidosLabel.setText("APELLIDOS");

		animalesTable
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] {

						}, new String[] { "NOMBRE", "ESPECIE", "RAZA",
								"TIPO DE PELO", "CAPA", "SEXO", "ESTERILIZADO",
								"PROPIETARIO", "DNI" }) {
					@SuppressWarnings("rawtypes")
					Class[] types = new Class[] { java.lang.String.class,
							java.lang.String.class, java.lang.String.class,
							java.lang.String.class, java.lang.String.class,
							java.lang.String.class, java.lang.String.class,
							java.lang.String.class, java.lang.String.class };
					boolean[] canEdit = new boolean[] { false, false, false,
							false, false, false, false, false, false };

					@SuppressWarnings("rawtypes")
					public Class getColumnClass(int columnIndex) {
						return types[columnIndex];
					}

					public boolean isCellEditable(int rowIndex, int columnIndex) {
						return canEdit[columnIndex];
					}
				});
		animalesTable.setColumnSelectionAllowed(true);
		animalesTable.getTableHeader().setReorderingAllowed(false);
		jScrollPane2.setViewportView(animalesTable);
		animalesTable
				.getColumnModel()
				.getSelectionModel()
				.setSelectionMode(
						javax.swing.ListSelectionModel.SINGLE_SELECTION);
		if (animalesTable.getColumnModel().getColumnCount() > 0) {
			animalesTable.getColumnModel().getColumn(0).setResizable(false);
			animalesTable.getColumnModel().getColumn(1).setResizable(false);
			animalesTable.getColumnModel().getColumn(2).setResizable(false);
			animalesTable.getColumnModel().getColumn(3).setResizable(false);
			animalesTable.getColumnModel().getColumn(4).setResizable(false);
			animalesTable.getColumnModel().getColumn(5).setResizable(false);
			animalesTable.getColumnModel().getColumn(6).setResizable(false);
			animalesTable.getColumnModel().getColumn(7).setResizable(false);
			animalesTable.getColumnModel().getColumn(8).setResizable(false);
		}

		nombreLabel1.setText("NOMBRE ANIMAL");

		buscarAnimales.setText("BUSCAR");
		buscarAnimales.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buscarAnimalesActionPerformed(evt);
			}
		});

		volverButton1.setText("VOLVER ATRAS");
		volverButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				volverButton1ActionPerformed(evt);
			}
		});

		salirButton1.setText("SALIR");
		salirButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				salirButton1ActionPerformed(evt);
			}
		});

		razaLabel.setText("RAZA");

		fichaClienteButton.setText("VER FICHA CLIENTE");
		fichaClienteButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						fichaClienteButtonActionPerformed(evt);
					}
				});

		fichaAnimalButton.setText("VER FICHA ANIMAL");
		fichaAnimalButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						fichaAnimalButtonActionPerformed(evt);
					}
				});

		jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36));
		jLabel2.setText("BUSCAMASCOTAS");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(75, 75, 75)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						nombreLabel1)
																				.addComponent(
																						razaLabel))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						nombreText1)
																				.addComponent(
																						razaText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						338,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						nombreLabel)
																				.addComponent(
																						apellidosLabel))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						apellidosText)
																				.addComponent(
																						nombreText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						338,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		fichaAnimalButton)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		buscarAnimales)
																.addGap(47, 47,
																		47)
																.addComponent(
																		volverButton1)
																.addGap(41, 41,
																		41)
																.addComponent(
																		salirButton1)
																.addGap(284,
																		284,
																		284)
																.addComponent(
																		fichaClienteButton)))
								.addGap(73, 73, 73))
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														1328,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
								.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jLabel2)
								.addGap(29, 29, 29)
								.addComponent(jScrollPane2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										285,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										65, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		nombreLabel1)
																.addComponent(
																		nombreText1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		nombreText,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		nombreLabel)))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		razaText,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		razaLabel))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		apellidosText,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		apellidosLabel)))
								.addGap(37, 37, 37)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(volverButton1)
												.addComponent(buscarAnimales)
												.addComponent(salirButton1)
												.addComponent(
														fichaClienteButton)
												.addComponent(fichaAnimalButton))
								.addGap(22, 22, 22)));

		pack();
		setLocationRelativeTo(null);
	}

	private void apellidosTextActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void buscarAnimalesActionPerformed(java.awt.event.ActionEvent evt) {
		String nombreAnimal = nombreText1.getText();
		String razaAnimal = razaText.getText();

		String nombreCliente = nombreText.getText();
		String apellidoCliente = apellidosText.getText();

		String sel = "";
		setSql("");
		boolean like = comprobarApellido(apellidoCliente);
		boolean realizarConsultaAnimal = false;

		String query;
		if (like) {

			apellidoCliente = getApellido1();

		}

		query = "LIKE " + apellidoCliente;

		if ((!nombreAnimal.equals("")) && (!razaAnimal.equals(""))) {
			sel = "NOM_ANIMAL, ESPECIE, RAZA, TIPO_PELO, CAPA, SEXO, ESTERILIZADO, FECHA_NACIMIENTO, ID_CLIENTE";
			setSql("SELECT " + sel + " FROM ANIMALES WHERE NOM_ANIMAL LIKE '%"
					+ nombreAnimal + "%' AND RAZA LIKE '%" + razaAnimal + "%'");
			realizarConsultaAnimal = true;
		} else {
			if (!nombreAnimal.equals("")) {
				sel = "NOM_ANIMAL, ESPECIE, RAZA, TIPO_PELO, CAPA, SEXO, ESTERILIZADO, FECHA_NACIMIENTO, ID_CLIENTE";
				setSql("SELECT " + sel
						+ " FROM ANIMALES WHERE NOM_ANIMAL LIKE '%"
						+ nombreAnimal + "%'");
				realizarConsultaAnimal = true;

			} else {
				if (!razaAnimal.equals("")) {
					sel = "NOM_ANIMAL, ESPECIE, RAZA, TIPO_PELO, CAPA, SEXO, ESTERILIZADO, FECHA_NACIMIENTO, ID_CLIENTE";
					setSql("SELECT " + sel
							+ " FROM ANIMALES WHERE RAZA LIKE '%" + razaAnimal
							+ "%'");
					realizarConsultaAnimal = true;

				} else {
					if ((!nombreCliente.equals(""))
							&& (!apellidoCliente.equals(""))) {
						sel = "NOM_CLIENTE, APELLIDOS, DNI";
						setSql("SELECT " + sel
								+ " FROM CLIENTES WHERE NOM_CLIENTE LIKE '%"
								+ nombreCliente + "%' AND APELLIDOS " + query
								+ "");

					} else {
						if (!nombreCliente.equals("")) {
							sel = "NOM_CLIENTE, APELLIDOS, DNI";
							setSql("SELECT "
									+ sel
									+ " FROM CLIENTES WHERE NOM_CLIENTE LIKE '%"
									+ nombreCliente + "%' ");

						} else {
							if (!apellidoCliente.equals("")) {
								sel = "NOM_CLIENTE, APELLIDOS, DNI";
								setSql("SELECT " + sel
										+ " FROM CLIENTES WHERE APELLIDOS "
										+ query + "");

							}
						}

					}

				}
			}
		}

		if (realizarConsultaAnimal == true) {
			DefaultTableModel tableModel = (DefaultTableModel) animalesTable
					.getModel();
			int cont = tableModel.getRowCount();

			for (int i = cont; i > 0; i--) {
				tableModel.removeRow(i - 1);
			}

			tableModel = consult.consultaAnimal(getSql(), tableModel);
			animalesTable.setModel(tableModel);
		} else {
			DefaultTableModel tableModel = (DefaultTableModel) animalesTable
					.getModel();
			int cont = tableModel.getRowCount();

			for (int i = cont; i > 0; i--) {
				tableModel.removeRow(i - 1);
			}
			tableModel = consult.consultaCliente(getSql(), tableModel);
			animalesTable.setModel(tableModel);
		}

	}

	private boolean comprobarApellido(String apellido) {
		String apell1, apellido2;
		apell1 = apellido.trim();
		int tamanyo = apell1.length();
		boolean like = false;
		apellido2 = apellido.substring(tamanyo);

		if (apellido2.equals("")) {
			setApellido1("'%" + apell1 + "%'");
			like = true;
			return like;
		} else {
			setApellido1("'%" + apellido + "%'");
			like = false;
			return like;
		}

	}

	private void volverButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		MenuPrincipal.main();
		this.setVisible(false);
	}

	private void salirButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea salir?");

		if (eleccion == 0) {
			JOptionPane.showMessageDialog(null, "Saliendo del sistema");
			System.exit(0);
		}
	}

	private void fichaClienteButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		int row = animalesTable.getSelectedRow();

		ResultSet resultado = null;
		resultado = consult.consultar("SELECT * FROM CLIENTES WHERE DNI = \""
				+ animalesTable.getValueAt(row, 8) + "\"");

		if (resultado != null) {

			int numeroColumna = 0;
			try {
				numeroColumna = resultado.getMetaData().getColumnCount();
			} catch (SQLException ex) {
				Logger.getLogger(BuscarAnimal.class.getName()).log(
						Level.SEVERE, null, ex);
			}

			objetos = new Object[numeroColumna];
			for (int i = 1; i <= numeroColumna; i++) {
				try {
					setObjetos(i - 1, resultado.getObject(i));
				} catch (SQLException ex) {
					Logger.getLogger(BuscarAnimal.class.getName()).log(
							Level.SEVERE, null, ex);
				}
			}

		}
		try {

			resultado.close();
		} catch (SQLException ex) {
			Logger.getLogger(BuscarAnimal.class.getName()).log(Level.SEVERE,
					null, ex);
		}

		FichaCliente.main(objetos);
		this.setVisible(false);
	}

	private void fichaAnimalButtonActionPerformed(java.awt.event.ActionEvent evt) {
		int row = animalesTable.getSelectedRow();

		ResultSet resultado = null;
		resultado = consult
				.consultar("SELECT * FROM ANIMALES WHERE ID_CLIENTE = \""
						+ animalesTable.getValueAt(row, 8)
						+ "\" AND NOM_ANIMAL = \""
						+ animalesTable.getValueAt(row, 0) + "\"");

		if (resultado != null) {

			int numeroColumna = 0;
			try {
				numeroColumna = resultado.getMetaData().getColumnCount();
			} catch (SQLException ex) {
				Logger.getLogger(BuscarAnimal.class.getName()).log(
						Level.SEVERE, null, ex);
			}

			objetos = new Object[numeroColumna];
			for (int i = 1; i <= numeroColumna; i++) {
				try {
					setObjetos(i - 1, resultado.getObject(i));
				} catch (SQLException ex) {
					Logger.getLogger(BuscarAnimal.class.getName()).log(
							Level.SEVERE, null, ex);
				}
			}

		}
		try {
			resultado.close();
		} catch (SQLException ex) {
			Logger.getLogger(BuscarAnimal.class.getName()).log(Level.SEVERE,
					null, ex);
		}
		FichaAnimal.main(objetos);
		this.setVisible(false);
	}

	public void volver() {
		this.setVisible(true);
	}

	public void salir() {
		setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent we) {

				int devolucion = JOptionPane.showConfirmDialog(null,
						"¿ESTA USTED SEGURO DE QUE DESEA SALIR?");
				if (devolucion == 0) {
					// TODO agregar subida de datos a dropbox. COPIA DE
					// SEGURIDAD.
					System.exit(0);
				}

			}
		});
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main() {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(BuscarAnimal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(BuscarAnimal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(BuscarAnimal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(BuscarAnimal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BuscarAnimal().setVisible(true);

			}
		});
	}

	// Declaración de variables
	private javax.swing.JTable animalesTable;
	private javax.swing.JLabel apellidosLabel;
	private javax.swing.JTextField apellidosText;
	private javax.swing.JButton buscarAnimales;
	private javax.swing.JButton fichaAnimalButton;
	private javax.swing.JButton fichaClienteButton;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JLabel nombreLabel;
	private javax.swing.JLabel nombreLabel1;
	private javax.swing.JTextField nombreText;
	private javax.swing.JTextField nombreText1;
	private javax.swing.JLabel razaLabel;
	private javax.swing.JTextField razaText;
	private javax.swing.JButton salirButton1;
	private javax.swing.JButton volverButton1;

}
