/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscamascotas.IU;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import buscamascotas.sqliteconection.Operaciones.Operaciones;

/**
 *
 * @author Alberto
 */
public class FichaCliente extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8616446857805667984L;
	static Object[] datos;
	Operaciones op = new Operaciones();
	String dni, nombre, apellidos, direccion, localidad, cp, municipio,
			telefono1, telefono2;
	BuscarAnimal busco = new BuscarAnimal();
	String sql;

	public String getSQL() {
		return sql;
	}

	public void setSQL(String sql) {
		this.sql = sql;
	}

	/**
	 * Creates new form FichaCliente
	 */
	public FichaCliente(Object[] param) {
		initComponents();

		datos = param;

		dniText.setText(datos[1].toString());
		nombreText.setText(datos[2].toString());
		apellidosText.setText(datos[3].toString());
		direccionText.setText(datos[4].toString());
		localidadText.setText(datos[5].toString());
		cpText.setText(datos[6].toString());
		municipioText.setText(datos[7].toString());
		telefonoText.setText(datos[8].toString());
		telefono2Text.setText(datos[9].toString());

		DefaultTableModel tableModel = (DefaultTableModel) animalTable
				.getModel();
		int cont = tableModel.getRowCount();

		for (int i = cont; i > 0; i--) {
			tableModel.removeRow(i - 1);
		}
		String sel = "NOM_ANIMAL, ESPECIE, RAZA";
		String sql = "SELECT " + sel + " FROM ANIMALES WHERE ID_CLIENTE = \""
				+ dniText.getText() + "\"";
		ResultSet result = op.consultar(sql);
		try {
			int num = result.getMetaData().getColumnCount();
			while (result.next()) {
				Object[] objetos = new Object[num];
				for (int i = 1; i <= num; i++) {
					objetos[i - 1] = result.getObject(i);
				}
				tableModel.addRow(objetos);
			}

			animalTable.setModel(tableModel);
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			try {

				op.desconectar();
				if (result != null) {
					result.close();
				}
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		salir();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings({ "unchecked", "serial" })
	private void initComponents() {

		direccionText = new javax.swing.JTextField();
		localidadLabel = new javax.swing.JLabel();
		localidadText = new javax.swing.JTextField();
		apellidosText = new javax.swing.JTextField();
		telefonoText = new javax.swing.JTextField();
		nombreText = new javax.swing.JTextField();
		nombreLabel = new javax.swing.JLabel();
		apellidosLabel = new javax.swing.JLabel();
		dniLabel = new javax.swing.JLabel();
		cpText = new javax.swing.JTextField();
		cpLabel = new javax.swing.JLabel();
		municipioLabel = new javax.swing.JLabel();
		telefonoLabel = new javax.swing.JLabel();
		dniText = new javax.swing.JTextField();
		direccionLabel = new javax.swing.JLabel();
		telefono2Text = new javax.swing.JTextField();
		telefono2Label = new javax.swing.JLabel();
		municipioText = new javax.swing.JTextField();
		actualizarButton = new javax.swing.JButton();
		eliminarButton = new javax.swing.JButton();
		menuButton = new javax.swing.JButton();
		salirButton = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		animalTable = new javax.swing.JTable();
		animalButton = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		localidadLabel.setText("LOCALIDAD ");

		nombreLabel.setText("NOMBRE");

		apellidosLabel.setText("APELLIDOS");

		dniLabel.setText("DNI");

		cpLabel.setText("CODIGO POSTAL");

		municipioLabel.setText("MUNICIPIO");

		telefonoLabel.setText("TELEFONO");

		direccionLabel.setText("DIRECCION");

		telefono2Label.setText("TELEFONO 2");

		actualizarButton.setText("GUARDAR CAMBIOS");
		actualizarButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				actualizarButtonActionPerformed(evt);
			}
		});

		eliminarButton.setText("ELIMINAR CLIENTE");
		eliminarButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				eliminarButtonActionPerformed(evt);
			}
		});

		menuButton.setText("MENU PRINCIPAL");
		menuButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				menuButtonActionPerformed(evt);
			}
		});

		salirButton.setText("SALIR");
		salirButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				salirButtonActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36));
		jLabel2.setText("BUSCAMASCOTAS");

		animalTable.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "NOMBRE", "ESPECIE", "RAZA" }) {
			@SuppressWarnings("rawtypes")
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class, java.lang.String.class };
			boolean[] canEdit = new boolean[] { true, false, false };

			@SuppressWarnings("rawtypes")
			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		animalTable.setColumnSelectionAllowed(true);
		jScrollPane1.setViewportView(animalTable);
		animalTable
				.getColumnModel()
				.getSelectionModel()
				.setSelectionMode(
						javax.swing.ListSelectionModel.SINGLE_SELECTION);
		if (animalTable.getColumnModel().getColumnCount() > 0) {
			animalTable.getColumnModel().getColumn(0).setResizable(false);
			animalTable.getColumnModel().getColumn(1).setResizable(false);
			animalTable.getColumnModel().getColumn(2).setResizable(false);
		}

		animalButton.setText("FICHA ANIMAL");
		animalButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				animalButtonActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
		jLabel3.setText("ANIMAL");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
		jLabel4.setText("CLIENTE");

		anyadirAnimalButton = new JButton("A\u00D1ADIR ANIMAL");
		anyadirAnimalButton.addActionListener(new ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				anyadirAnimalButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(10)
								.addGroup(
										layout.createParallelGroup(
												Alignment.TRAILING)
												.addComponent(eliminarButton)
												.addGroup(
														layout.createParallelGroup(
																Alignment.LEADING)
																.addGroup(
																		layout.createSequentialGroup()
																				.addGap(91)
																				.addGroup(
																						layout.createParallelGroup(
																								Alignment.LEADING)
																								.addComponent(
																										actualizarButton)
																								.addGroup(
																										layout.createSequentialGroup()
																												.addGroup(
																														layout.createParallelGroup(
																																Alignment.LEADING)
																																.addGroup(
																																		layout.createParallelGroup(
																																				Alignment.LEADING,
																																				false)
																																				.addComponent(
																																						apellidosLabel,
																																						GroupLayout.DEFAULT_SIZE,
																																						GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						nombreLabel,
																																						GroupLayout.DEFAULT_SIZE,
																																						GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						dniLabel,
																																						Alignment.TRAILING,
																																						GroupLayout.DEFAULT_SIZE,
																																						GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						direccionLabel,
																																						GroupLayout.DEFAULT_SIZE,
																																						GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						localidadLabel,
																																						Alignment.TRAILING,
																																						GroupLayout.PREFERRED_SIZE,
																																						82,
																																						GroupLayout.PREFERRED_SIZE))
																																.addGroup(
																																		layout.createParallelGroup(
																																				Alignment.TRAILING,
																																				false)
																																				.addComponent(
																																						telefono2Label,
																																						Alignment.LEADING,
																																						GroupLayout.DEFAULT_SIZE,
																																						GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						telefonoLabel,
																																						Alignment.LEADING,
																																						GroupLayout.DEFAULT_SIZE,
																																						GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						municipioLabel,
																																						Alignment.LEADING,
																																						GroupLayout.DEFAULT_SIZE,
																																						GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						cpLabel,
																																						Alignment.LEADING)))
																												.addGap(69)
																												.addGroup(
																														layout.createParallelGroup(
																																Alignment.LEADING)
																																.addComponent(
																																		jLabel4)
																																.addGroup(
																																		layout.createParallelGroup(
																																				Alignment.LEADING,
																																				false)
																																				.addComponent(
																																						dniText)
																																				.addComponent(
																																						nombreText)
																																				.addComponent(
																																						apellidosText)
																																				.addComponent(
																																						direccionText)
																																				.addComponent(
																																						localidadText,
																																						GroupLayout.PREFERRED_SIZE,
																																						242,
																																						GroupLayout.PREFERRED_SIZE)
																																				.addComponent(
																																						cpText)
																																				.addComponent(
																																						municipioText)
																																				.addComponent(
																																						telefonoText)
																																				.addComponent(
																																						telefono2Text,
																																						GroupLayout.PREFERRED_SIZE,
																																						242,
																																						GroupLayout.PREFERRED_SIZE))))))
																.addGroup(
																		layout.createSequentialGroup()
																				.addPreferredGap(
																						ComponentPlacement.RELATED)
																				.addComponent(
																						jLabel2))))
								.addGroup(
										layout.createParallelGroup(
												Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(36)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.LEADING,
																				false)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										animalButton)
																								.addPreferredGap(
																										ComponentPlacement.RELATED)
																								.addComponent(
																										anyadirAnimalButton)
																								.addPreferredGap(
																										ComponentPlacement.RELATED,
																										GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE)
																								.addComponent(
																										menuButton)
																								.addGap(18)
																								.addComponent(
																										salirButton))
																				.addComponent(
																						jScrollPane1,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE))
																.addContainerGap(
																		36,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addPreferredGap(
																		ComponentPlacement.RELATED,
																		216,
																		Short.MAX_VALUE)
																.addComponent(
																		jLabel3)
																.addGap(250)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jLabel2)
																.addPreferredGap(
																		ComponentPlacement.RELATED,
																		62,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap(
																		81,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.BASELINE)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jLabel4))
																.addGap(18)))
								.addGroup(
										layout.createParallelGroup(
												Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.BASELINE)
																				.addComponent(
																						dniLabel)
																				.addComponent(
																						dniText,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.BASELINE)
																				.addComponent(
																						nombreLabel)
																				.addComponent(
																						nombreText,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.BASELINE)
																				.addComponent(
																						apellidosLabel)
																				.addComponent(
																						apellidosText,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.BASELINE)
																				.addComponent(
																						direccionLabel)
																				.addComponent(
																						direccionText,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.BASELINE)
																				.addComponent(
																						localidadLabel)
																				.addComponent(
																						localidadText,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.BASELINE)
																				.addComponent(
																						cpLabel)
																				.addComponent(
																						cpText,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.BASELINE)
																				.addComponent(
																						municipioLabel)
																				.addComponent(
																						municipioText,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.BASELINE)
																				.addComponent(
																						telefonoLabel)
																				.addComponent(
																						telefonoText,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.BASELINE)
																				.addComponent(
																						telefono2Label)
																				.addComponent(
																						telefono2Text,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.BASELINE)
																				.addComponent(
																						actualizarButton)
																				.addComponent(
																						eliminarButton)
																				.addComponent(
																						menuButton)
																				.addComponent(
																						salirButton)
																				.addComponent(
																						animalButton)
																				.addComponent(
																						anyadirAnimalButton)))
												.addComponent(
														jScrollPane1,
														GroupLayout.PREFERRED_SIZE,
														268,
														GroupLayout.PREFERRED_SIZE))
								.addContainerGap()));
		getContentPane().setLayout(layout);

		pack();
		setLocationRelativeTo(null);
	}

	protected void anyadirAnimalButtonActionPerformed(ActionEvent evt) {
		InsertarAnimal.main(dniText.getText());
		this.setVisible(false);
	}

	private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {

		PopUpWindow hola = new PopUpWindow(this, rootPaneCheckingEnabled);
		String textoLabel;

		textoLabel = "¿Desea eliminar a " + nombreText.getText().toString();

		textoLabel = textoLabel + " " + apellidosText.getText().toString()
				+ " de BUSCAMASCOTAS?";

		hola.setLabelPopup(textoLabel);
		hola.setVisible(true);
		if (hola.getReturnStatus() == 1) {
			setSQL("DELETE FROM CLIENTES WHERE DNI = \"" + dniText.getText()
					+ "\"");

			op.insertar(getSQL());

			dniText.setText("");
			nombreText.setText("");
			apellidosText.setText("");
			direccionText.setText("");
			localidadText.setText("");
			cpText.setText("");
			municipioText.setText("");
			telefonoText.setText("");
			telefono2Text.setText("");

			animalTable.removeAll();
		}
	}

	private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {
		dni = dniText.getText();
		nombre = nombreText.getText();
		apellidos = apellidosText.getText();
		direccion = direccionText.getText();
		localidad = localidadText.getText();
		cp = cpText.getText();
		municipio = municipioText.getText();
		telefono1 = telefonoText.getText();
		telefono2 = telefono2Text.getText();

		PopUpWindow hola = new PopUpWindow(this, rootPaneCheckingEnabled);
		String textoLabel;

		if (nombre.equals("")) {
			textoLabel = "¿Dese actualizar a  ";
		} else {
			textoLabel = "¿Desea actualizar a " + nombre;
		}
		if (apellidos.equals("")) {
			textoLabel = textoLabel + "   en BUSCAMASCOTAS?";
		} else {
			textoLabel = textoLabel + " " + apellidos + " en BUSCAMASCOTAS?";
		}

		hola.setLabelPopup(textoLabel);
		hola.setVisible(true);
		if (hola.getReturnStatus() == 1) {
			setSQL("UPDATE CLIENTES SET DNI ='" + dni + "', NOM_CLIENTE='"
					+ nombre + "',APELLIDOS='" + apellidos + "',"
					+ "DIRECCION='" + direccion + "',LOCALIDAD='" + localidad
					+ "', CP='" + cp + "',MUNICIPIO='" + municipio + "',"
					+ "TELEFONO1='" + telefono1 + "',TELEFONO2='" + telefono2
					+ "'WHERE DNI = \"" + datos[1].toString() + "\"");
			op.insertar(getSQL());

			setSQL("UPDATE ANIMALES SET ID_CLIENTE = '" + dni
					+ "' WHERE ID_CLIENTE = \"" + datos[1].toString() + "\"");

			op.insertar(getSQL());

			datos[1] = dni;
			dniText.setText(datos[1].toString());
			nombreText.setText(nombre);
			apellidosText.setText(apellidos);
			direccionText.setText(direccion);
			localidadText.setText(localidad);
			cpText.setText(cp);
			municipioText.setText(municipio);
			telefonoText.setText(telefono1);
			telefono2Text.setText(telefono2);
		}
	}

	private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {
		MenuPrincipal.main();
		this.setVisible(false);
	}

	private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {
		int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea salir?");

		if (eleccion == 0) {
			JOptionPane.showMessageDialog(null, "Saliendo del sistema");
			System.exit(0);
		}
	}

	private void animalButtonActionPerformed(java.awt.event.ActionEvent evt) {

		int linea = animalTable.getSelectedRow();
		String nombreAnimal = animalTable.getValueAt(linea, 0).toString();
		String especie = animalTable.getValueAt(linea, 1).toString();
		String raza = animalTable.getValueAt(linea, 2).toString();
		String id = dniText.getText().toString();
		PopUpWindow hola = new PopUpWindow(this, rootPaneCheckingEnabled);

		hola.setLabelPopup("¿DESEA VER LOS DATOS DE " + nombreAnimal + " ?");
		hola.setVisible(true);
		if (hola.getReturnStatus() == 1) {

			setSQL("SELECT * FROM ANIMALES WHERE NOM_ANIMAL = \""
					+ nombreAnimal + "\" AND " + "ESPECIE = \"" + especie
					+ "\" AND RAZA = \"" + raza + "\" AND ID_CLIENTE =" + " \""
					+ id + "\"");

			ResultSet animalEntero = op.consultar(getSQL());

			try {
				int num = animalEntero.getMetaData().getColumnCount();

				Object[] animalParam = new Object[num];

				for (int i = 1; i <= num; i++) {
					animalParam[i - 1] = animalEntero.getObject(i);
				}
				op.desconectar();
				FichaAnimal.main(animalParam);
				this.setVisible(false);
			} catch (SQLException ex) {
				Logger.getLogger(FichaCliente.class.getName()).log(
						Level.SEVERE, null, ex);
			}
		}

	}

	public void salir() {
		setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent we) {

				int devolucion = JOptionPane.showConfirmDialog(null,
						"¿ESTA USTED SEGURO DE QUE DESEA SALIR?");

				if (devolucion == 0) {
					// TODO agregar subida de datos a dropbox. COPIA DE
					// SEGURIDAD.
					System.exit(0);
				}

			}
		});
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(final Object[] param1) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FichaCliente.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FichaCliente.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FichaCliente.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FichaCliente.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {

				new FichaCliente(param1).setVisible(true);

			}
		});
	}

	// Declaración de variables
	private javax.swing.JButton actualizarButton;
	private javax.swing.JButton animalButton;
	private javax.swing.JTable animalTable;
	private javax.swing.JLabel apellidosLabel;
	private javax.swing.JTextField apellidosText;
	private javax.swing.JLabel cpLabel;
	private javax.swing.JTextField cpText;
	private javax.swing.JLabel direccionLabel;
	private javax.swing.JTextField direccionText;
	private javax.swing.JLabel dniLabel;
	private javax.swing.JTextField dniText;
	private javax.swing.JButton eliminarButton;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel localidadLabel;
	private javax.swing.JTextField localidadText;
	private javax.swing.JButton menuButton;
	private javax.swing.JLabel municipioLabel;
	private javax.swing.JTextField municipioText;
	private javax.swing.JLabel nombreLabel;
	private javax.swing.JTextField nombreText;
	private javax.swing.JButton salirButton;
	private javax.swing.JLabel telefono2Label;
	private javax.swing.JTextField telefono2Text;
	private javax.swing.JLabel telefonoLabel;
	private javax.swing.JTextField telefonoText;
	private JButton anyadirAnimalButton;

}
