package buscamascotas.IU;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

import buscamascotas.sqliteconection.Operaciones.Operaciones;

/**
 *
 * @author Alberto
 */
public class FichaAnimal extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4004304338381682434L;
	static Object[] datos, cliente;
	Operaciones op = new Operaciones();

	String sql;

	public String getSQL() {
		return sql;
	}

	public void setSQL(String sql) {
		this.sql = sql;
	}

	/**
	 * Creates new form FichaAnimal
	 */
	public FichaAnimal() {
		initComponents();

		nombreText.setText(datos[1].toString());
		microchipText.setText(datos[2].toString());
		fechaMicroText.setText(datos[3].toString());
		sexoText.setText(datos[4].toString());
		especieText.setText(datos[5].toString());
		razaText.setText(datos[6].toString());
		peloText.setText(datos[7].toString());
		capaText.setText(datos[8].toString());
		dietaText.setText(datos[9].toString());
		habitatText.setText(datos[10].toString());
		nacimientoText.setText(datos[11].toString());
		esterilizadoText.setText(datos[12].toString());

		obtenerDuenyo();

		dniText.setText(cliente[1].toString());
		nombreText1.setText(cliente[2].toString());
		apellidosText.setText(cliente[3].toString());
		direccionText.setText(cliente[4].toString());
		localidadText.setText(cliente[5].toString());
		cpText.setText(cliente[6].toString());
		municipioText.setText(cliente[7].toString());
		telefonoText.setText(cliente[8].toString());
		telefono2Text.setText(cliente[9].toString());

		salir();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		salirButton = new javax.swing.JButton();
		menuButton = new javax.swing.JButton();
		actualizarButton = new javax.swing.JButton();
		eliminarButton = new javax.swing.JButton();
		fechaMicroText = new javax.swing.JTextField();
		sexoText = new javax.swing.JTextField();
		nombreText = new javax.swing.JTextField();
		razaText = new javax.swing.JTextField();
		capaText = new javax.swing.JTextField();
		dietaText = new javax.swing.JTextField();
		dietaLabel = new javax.swing.JLabel();
		sexoLabel = new javax.swing.JLabel();
		fechachipLabel = new javax.swing.JLabel();
		nacimientoText = new javax.swing.JTextField();
		peloText = new javax.swing.JTextField();
		nacimientoLabel = new javax.swing.JLabel();
		esterilizadoLabel = new javax.swing.JLabel();
		esterilizadoText = new javax.swing.JTextField();
		habitatText = new javax.swing.JTextField();
		esterilizadoLabel1 = new javax.swing.JLabel();
		peloLabel = new javax.swing.JLabel();
		capaLabel = new javax.swing.JLabel();
		microchipText = new javax.swing.JTextField();
		especieLabel = new javax.swing.JLabel();
		razaLabel = new javax.swing.JLabel();
		especieText = new javax.swing.JTextField();
		microchipLabel = new javax.swing.JLabel();
		nombreLabel = new javax.swing.JLabel();
		historialButton = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		telefonoLabel = new javax.swing.JLabel();
		telefono2Text = new javax.swing.JTextField();
		cpLabel = new javax.swing.JLabel();
		telefono2Label = new javax.swing.JLabel();
		municipioLabel = new javax.swing.JLabel();
		municipioText = new javax.swing.JTextField();
		dniLabel = new javax.swing.JLabel();
		cpText = new javax.swing.JTextField();
		nombreLabel1 = new javax.swing.JLabel();
		apellidosLabel = new javax.swing.JLabel();
		telefonoText = new javax.swing.JTextField();
		nombreText1 = new javax.swing.JTextField();
		direccionLabel = new javax.swing.JLabel();
		dniText = new javax.swing.JTextField();
		apellidosText = new javax.swing.JTextField();
		direccionText = new javax.swing.JTextField();
		localidadText = new javax.swing.JTextField();
		localidadLabel = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		clienteButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		salirButton.setText("SALIR");
		salirButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				salirButtonActionPerformed(evt);
			}
		});

		menuButton.setText("MENU PRINCIPAL");
		menuButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				menuButtonActionPerformed(evt);
			}
		});

		actualizarButton.setText("GUARDAR");
		actualizarButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				actualizarButtonActionPerformed(evt);
			}
		});

		eliminarButton.setText("ELIMINAR ANIMAL");
		eliminarButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				eliminarButtonActionPerformed(evt);
			}
		});

		dietaLabel.setText("DIETA");

		sexoLabel.setText("SEXO");

		fechachipLabel.setText("FECHA MICROCHIP");

		nacimientoLabel.setText("FECHA NACIMIENTO");

		esterilizadoLabel.setText("ESTERILIZADO");

		esterilizadoLabel1.setText("HABITAT");

		peloLabel.setText("TIPO DE PELO");

		capaLabel.setText("CAPA");

		especieLabel.setText("ESPECIE");

		razaLabel.setText("RAZA ");

		microchipLabel.setText("MICROCHIP");

		nombreLabel.setText("NOMBRE");

		historialButton.setText("VER HISTORIAL");
		historialButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				historialButtonActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36));
		jLabel1.setText("BUSCAMASCOTAS");

		telefonoLabel.setText("TELEFONO");

		cpLabel.setText("CODIGO POSTAL");

		telefono2Label.setText("TELEFONO 2");

		municipioLabel.setText("MUNICIPIO");

		dniLabel.setText("DNI");

		nombreLabel1.setText("NOMBRE");

		apellidosLabel.setText("APELLIDOS");

		direccionLabel.setText("DIRECCION");

		localidadLabel.setText("LOCALIDAD ");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
		jLabel2.setText("ANIMAL");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
		jLabel3.setText("CLIENTE");

		clienteButton.setText("FICHA CLIENTE");
		clienteButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				clienteButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(97, 97, 97)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addContainerGap(
																		573,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																								.addGroup(
																										layout.createSequentialGroup()
																												.addComponent(
																														especieLabel)
																												.addPreferredGap(
																														javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)
																												.addComponent(
																														especieText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														242,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGroup(
																										layout.createSequentialGroup()
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING,
																																				false)
																																				.addComponent(
																																						fechachipLabel,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						microchipLabel,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						nombreLabel,
																																						javax.swing.GroupLayout.Alignment.TRAILING,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						sexoLabel,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						94,
																																						javax.swing.GroupLayout.PREFERRED_SIZE))
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.TRAILING,
																																				false)
																																				.addComponent(
																																						dietaLabel,
																																						javax.swing.GroupLayout.Alignment.LEADING,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						capaLabel,
																																						javax.swing.GroupLayout.Alignment.LEADING,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						peloLabel,
																																						javax.swing.GroupLayout.Alignment.LEADING))
																																.addComponent(
																																		razaLabel,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		82,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																		esterilizadoLabel1))
																												.addGap(24,
																														24,
																														24)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																																.addComponent(
																																		dietaText,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		242,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																		habitatText,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		242,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																		capaText,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		242,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																		peloText,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		242,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																		razaText,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		242,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																		sexoText,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		242,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																		fechaMicroText,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		242,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																		microchipText,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		242,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																		nombreText,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		242,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																		jLabel2))))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																												.addComponent(
																														nacimientoLabel,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)
																												.addComponent(
																														esterilizadoLabel,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE))
																								.addGap(18,
																										18,
																										18)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														esterilizadoText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														242,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														nacimientoText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														242,
																														javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										actualizarButton)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										eliminarButton)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										historialButton)))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										clienteButton)
																								.addGap(115,
																										115,
																										115)
																								.addComponent(
																										menuButton)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										salirButton))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																																.addComponent(
																																		apellidosLabel,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		nombreLabel1,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		dniLabel,
																																		javax.swing.GroupLayout.Alignment.TRAILING,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		direccionLabel,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		localidadLabel,
																																		javax.swing.GroupLayout.Alignment.TRAILING,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		82,
																																		javax.swing.GroupLayout.PREFERRED_SIZE))
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																false)
																																.addComponent(
																																		telefono2Label,
																																		javax.swing.GroupLayout.Alignment.LEADING,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		telefonoLabel,
																																		javax.swing.GroupLayout.Alignment.LEADING,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		municipioLabel,
																																		javax.swing.GroupLayout.Alignment.LEADING,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		cpLabel,
																																		javax.swing.GroupLayout.Alignment.LEADING)))
																								.addGap(69,
																										69,
																										69)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel3)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																																.addComponent(
																																		dniText)
																																.addComponent(
																																		nombreText1)
																																.addComponent(
																																		apellidosText)
																																.addComponent(
																																		direccionText)
																																.addComponent(
																																		localidadText,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		242,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																		cpText)
																																.addComponent(
																																		municipioText)
																																.addComponent(
																																		telefonoText)
																																.addComponent(
																																		telefono2Text,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		242,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)))))
																.addGap(79, 79,
																		79)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(jLabel3))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGap(423,
																		423,
																		423)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						actualizarButton)
																				.addComponent(
																						eliminarButton)
																				.addComponent(
																						historialButton)))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						dniLabel)
																				.addComponent(
																						dniText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						nombreLabel1)
																				.addComponent(
																						nombreText1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						apellidosLabel)
																				.addComponent(
																						apellidosText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						direccionLabel)
																				.addComponent(
																						direccionText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						localidadLabel)
																				.addComponent(
																						localidadText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						cpLabel)
																				.addComponent(
																						cpText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						municipioLabel)
																				.addComponent(
																						municipioText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						telefonoLabel)
																				.addComponent(
																						telefonoText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						telefono2Label)
																				.addComponent(
																						telefono2Text,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						menuButton)
																				.addComponent(
																						salirButton)
																				.addComponent(
																						clienteButton)))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						nombreLabel)
																				.addComponent(
																						nombreText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						microchipLabel)
																				.addComponent(
																						microchipText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						fechachipLabel)
																				.addComponent(
																						fechaMicroText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						sexoLabel)
																				.addComponent(
																						sexoText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						especieLabel)
																				.addComponent(
																						especieText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(11, 11,
																		11)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						razaLabel)
																				.addComponent(
																						razaText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						peloLabel)
																				.addComponent(
																						peloText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						capaLabel)
																				.addComponent(
																						capaText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						dietaLabel)
																				.addComponent(
																						dietaText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						esterilizadoLabel1)
																				.addComponent(
																						habitatText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(11, 11,
																		11)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						nacimientoText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						nacimientoLabel))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						esterilizadoLabel)
																				.addComponent(
																						esterilizadoText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(78, 78,
																		78)))
								.addContainerGap()));

		pack();
		setLocationRelativeTo(null);
	}

	private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {
		int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea salir?");

		if (eleccion == 0) {
			JOptionPane.showMessageDialog(null, "Saliendo del sistema");
			System.exit(0);
		}
	}

	private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {
		MenuPrincipal.main();
		this.setVisible(false);
	}

	private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {

		String nombre = nombreText.getText();
		String chip = microchipText.getText();
		String fechaChip = fechaMicroText.getText();
		String sexo = sexoText.getText();
		String especie = especieText.getText();
		String raza = razaText.getText();
		String pelo = peloText.getText();
		String capa = capaText.getText();
		String dieta = dietaText.getText();
		String habitat = habitatText.getText();
		String nacimiento = nacimientoText.getText();
		String esterilizado = esterilizadoText.getText();

		PopUpWindow hola = new PopUpWindow(this, rootPaneCheckingEnabled);
		String textoLabel;

		if (nombre.equals("")) {
			textoLabel = "¿Dese actualizar los datos en BUSCAMASCOTAS?";
		} else {
			textoLabel = "¿Desea actualizar a " + nombre + " en BUSCAMASCOTAS?";
		}

		hola.setLabelPopup(textoLabel);
		hola.setVisible(true);
		if (hola.getReturnStatus() == 1) {

			setSQL("UPDATE ANIMALES SET NOM_ANIMAL ='" + nombre
					+ "', MICROCHIP='" + chip + "',FECHA_CHIP='" + fechaChip
					+ "',SEXO='" + sexo + "'," + "ESPECIE='" + especie
					+ "', RAZA='" + raza + "',TIPO_PELO='" + pelo + "',CAPA='"
					+ capa + "'," + "DIETA='" + dieta + "', HABITAT = '"
					+ habitat + "', FECHA_NACIMIENTO = '" + nacimiento + "', "
					+ "ESTERILIZADO = '" + esterilizado
					+ "' WHERE ID_CLIENTE = \"" + datos[13].toString()
					+ "\" AND NOM_ANIMAL = \"" + datos[1].toString() + "\"");

			op.insertar(getSQL());

			datos[1] = nombre;
			nombreText.setText(nombre);
			microchipText.setText(chip);
			fechaMicroText.setText(fechaChip);
			sexoText.setText(sexo);
			especieText.setText(especie);
			razaText.setText(raza);
			peloText.setText(pelo);
			capaText.setText(capa);
			dietaText.setText(dieta);
			habitatText.setText(habitat);
			nacimientoText.setText(nacimiento);
			esterilizadoText.setText(esterilizado);
		}
	}

	private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {

		PopUpWindow hola = new PopUpWindow(this, rootPaneCheckingEnabled);
		String textoLabel;

		textoLabel = "¿Desea eliminar a " + nombreText.getText()
				+ " de BUSCAMASCOTAS?";

		hola.setLabelPopup(textoLabel);
		hola.setVisible(true);
		if (hola.getReturnStatus() == 1) {

			setSQL("DELETE FROM ANIMALES WHERE ID_CLIENTE = \""
					+ datos[13].toString() + "\" AND NOM_ANIMAL = \""
					+ nombreText.getText() + "\"");
			op.insertar(getSQL());
		}
	}

	private void historialButtonActionPerformed(java.awt.event.ActionEvent evt) {
		Historial.main(datos);
		this.setVisible(false);
	}

	private void clienteButtonActionPerformed(java.awt.event.ActionEvent evt) {
		PopUpWindow hola = new PopUpWindow(this, rootPaneCheckingEnabled);

		hola.setLabelPopup("¿DESEA VER LOS DATOS DE " + dniText.getText()
				+ " ?");
		hola.setVisible(true);
		if (hola.getReturnStatus() == 1) {
			FichaCliente.main(cliente);
			this.setVisible(false);
		}
	}

	public void salir() {
		setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent we) {

				int devolucion = JOptionPane.showConfirmDialog(null,
						"¿ESTA USTED SEGURO DE QUE DESEA SALIR?");
				if (devolucion == 0) {
					// TODO agregar subida de datos a dropbox. COPIA DE
					// SEGURIDAD.
					System.exit(0);
				}

			}
		});
	}

	public void obtenerDuenyo() {
		ResultSet resultado = null;
		resultado = op.consultar("SELECT * FROM CLIENTES WHERE DNI = \""
				+ datos[13].toString() + "\"");

		if (resultado != null) {

			int numeroColumna = 0;
			try {
				numeroColumna = resultado.getMetaData().getColumnCount();
			} catch (SQLException ex) {
				Logger.getLogger(BuscarAnimal.class.getName()).log(
						Level.SEVERE, null, ex);
			}

			Object[] objetos = new Object[numeroColumna];
			for (int i = 1; i <= numeroColumna; i++) {
				try {
					objetos[i - 1] = resultado.getObject(i);
				} catch (SQLException ex) {
					Logger.getLogger(BuscarAnimal.class.getName()).log(
							Level.SEVERE, null, ex);
				}
			}
			cliente = objetos;

		}
		try {

			resultado.close();
		} catch (SQLException ex) {
			Logger.getLogger(BuscarAnimal.class.getName()).log(Level.SEVERE,
					null, ex);
		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(final Object[] param1) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FichaAnimal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FichaAnimal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FichaAnimal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FichaAnimal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				datos = param1;
				new FichaAnimal().setVisible(true);

			}
		});
	}

	// Declaración de variables
	private javax.swing.JButton actualizarButton;
	private javax.swing.JLabel apellidosLabel;
	private javax.swing.JTextField apellidosText;
	private javax.swing.JLabel capaLabel;
	private javax.swing.JTextField capaText;
	private javax.swing.JButton clienteButton;
	private javax.swing.JLabel cpLabel;
	private javax.swing.JTextField cpText;
	private javax.swing.JLabel dietaLabel;
	private javax.swing.JTextField dietaText;
	private javax.swing.JLabel direccionLabel;
	private javax.swing.JTextField direccionText;
	private javax.swing.JLabel dniLabel;
	private javax.swing.JTextField dniText;
	private javax.swing.JButton eliminarButton;
	private javax.swing.JLabel especieLabel;
	private javax.swing.JTextField especieText;
	private javax.swing.JLabel esterilizadoLabel;
	private javax.swing.JLabel esterilizadoLabel1;
	private javax.swing.JTextField esterilizadoText;
	private javax.swing.JTextField fechaMicroText;
	private javax.swing.JLabel fechachipLabel;
	private javax.swing.JTextField habitatText;
	private javax.swing.JButton historialButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel localidadLabel;
	private javax.swing.JTextField localidadText;
	private javax.swing.JButton menuButton;
	private javax.swing.JLabel microchipLabel;
	private javax.swing.JTextField microchipText;
	private javax.swing.JLabel municipioLabel;
	private javax.swing.JTextField municipioText;
	private javax.swing.JLabel nacimientoLabel;
	private javax.swing.JTextField nacimientoText;
	private javax.swing.JLabel nombreLabel;
	private javax.swing.JLabel nombreLabel1;
	private javax.swing.JTextField nombreText;
	private javax.swing.JTextField nombreText1;
	private javax.swing.JLabel peloLabel;
	private javax.swing.JTextField peloText;
	private javax.swing.JLabel razaLabel;
	private javax.swing.JTextField razaText;
	private javax.swing.JButton salirButton;
	private javax.swing.JLabel sexoLabel;
	private javax.swing.JTextField sexoText;
	private javax.swing.JLabel telefono2Label;
	private javax.swing.JTextField telefono2Text;
	private javax.swing.JLabel telefonoLabel;
	private javax.swing.JTextField telefonoText;
}
