package buscamascotas.IU;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;

import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

import buscamascotas.sqliteconection.Operaciones.Conexion;
import buscamascotas.sqliteconection.Operaciones.Operaciones;

/**
 *
 * @author Alberto
 */
public class InsertarAnimal extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1568477946399764726L;
	Operaciones ins = new Operaciones();
	Conexion con = new Conexion();
	private String sql;
	private String ruta, especie, raza, nombre, carpeta;

	public String getSql() {
		return sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}

	/**
	 * Creates new form InsertarAnimal
	 */
	public InsertarAnimal() {
		initComponents();

		salir();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		capaLabel = new javax.swing.JLabel();
		peloLabel = new javax.swing.JLabel();
		especieText = new javax.swing.JTextField();
		animalButton = new javax.swing.JButton();
		razaLabel = new javax.swing.JLabel();
		especieLabel = new javax.swing.JLabel();
		nombreLabel = new javax.swing.JLabel();
		microchipLabel = new javax.swing.JLabel();
		microchipText = new javax.swing.JTextField();
		sexoLabel = new javax.swing.JLabel();
		fechachipLabel = new javax.swing.JLabel();
		dietaText = new javax.swing.JTextField();
		dietaLabel = new javax.swing.JLabel();
		razaText = new javax.swing.JTextField();
		capaText = new javax.swing.JTextField();
		sexoText = new javax.swing.JTextField();
		nombreText = new javax.swing.JTextField();
		fechaMicroText = new javax.swing.JTextField();
		peloText = new javax.swing.JTextField();
		nacimientoText = new javax.swing.JTextField();
		nacimientoLabel = new javax.swing.JLabel();
		esterilizadoLabel = new javax.swing.JLabel();
		esterilizadoText = new javax.swing.JTextField();
		habitatText = new javax.swing.JTextField();
		esterilizadoLabel1 = new javax.swing.JLabel();
		principalButton = new javax.swing.JButton();
		atrasButton = new javax.swing.JButton();
		salirButton = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		capaLabel.setText("CAPA");

		peloLabel.setText("TIPO DE PELO");

		animalButton.setText("GUARDAR");
		animalButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				animalButtonActionPerformed(evt);
			}
		});

		razaLabel.setText("RAZA ");

		especieLabel.setText("ESPECIE");

		nombreLabel.setText("NOMBRE");

		microchipLabel.setText("MICROCHIP");

		sexoLabel.setText("SEXO");

		fechachipLabel.setText("FECHA MICROCHIP");

		dietaLabel.setText("DIETA");

//		nacimientoText.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				nacimientoTextActionPerformed(evt);
//			}
//		});

		nacimientoLabel.setText("FECHA NACIMIENTO");

		esterilizadoLabel.setText("ESTERILIZADO");

		esterilizadoLabel1.setText("HABITAT");

		principalButton.setText("MENU PRINCIPAL");
		principalButton.setToolTipText("");
		principalButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				principalButtonActionPerformed(evt);
			}
		});

		atrasButton.setText("VOLVER ATRAS");
		atrasButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				atrasButtonActionPerformed(evt);
			}
		});

		salirButton.setText("SALIR");
		salirButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				salirButtonActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36));
		jLabel2.setText("BUSCAMASCOTAS");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup().addGap(41, 41, 41)
								.addComponent(animalButton).addGap(18, 18, 18)
								.addComponent(principalButton)
								.addGap(26, 26, 26).addComponent(atrasButton)
								.addGap(38, 38, 38).addComponent(salirButton)
								.addGap(0, 62, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jLabel2))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(88, 88,
																		88)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						layout.createSequentialGroup()
																								.addComponent(
																										nacimientoLabel)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										nacimientoText,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										242,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						layout.createSequentialGroup()
																								.addComponent(
																										esterilizadoLabel)
																								.addGap(46,
																										46,
																										46)
																								.addComponent(
																										esterilizadoText,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										242,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																																.addComponent(
																																		fechachipLabel,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		microchipLabel,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		nombreLabel,
																																		javax.swing.GroupLayout.Alignment.TRAILING,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		sexoLabel,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		94,
																																		javax.swing.GroupLayout.PREFERRED_SIZE))
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																false)
																																.addComponent(
																																		dietaLabel,
																																		javax.swing.GroupLayout.Alignment.LEADING,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		capaLabel,
																																		javax.swing.GroupLayout.Alignment.LEADING,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		peloLabel,
																																		javax.swing.GroupLayout.Alignment.LEADING))
																												.addComponent(
																														esterilizadoLabel1)
																												.addComponent(
																														especieLabel)
																												.addComponent(
																														razaLabel,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														82,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(24,
																										24,
																										24)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														razaText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														242,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														especieText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														242,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														dietaText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														242,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														habitatText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														242,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														capaText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														242,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														peloText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														242,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														sexoText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														242,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														fechaMicroText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														242,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														microchipText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														242,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														nombreText,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														242,
																														javax.swing.GroupLayout.PREFERRED_SIZE))))))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel2)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										22, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(nombreLabel)
												.addComponent(
														nombreText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(microchipLabel)
												.addComponent(
														microchipText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(fechachipLabel)
												.addComponent(
														fechaMicroText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(sexoLabel)
												.addComponent(
														sexoText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(especieLabel)
												.addComponent(
														especieText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(11, 11, 11)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(razaLabel)
												.addComponent(
														razaText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(peloLabel)
												.addComponent(
														peloText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(capaLabel)
												.addComponent(
														capaText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(dietaLabel)
												.addComponent(
														dietaText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														esterilizadoLabel1)
												.addComponent(
														habitatText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(11, 11, 11)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														nacimientoText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(nacimientoLabel))
								.addGap(9, 9, 9)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(esterilizadoLabel)
												.addComponent(
														esterilizadoText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(57, 57, 57)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(animalButton)
												.addComponent(principalButton)
												.addComponent(atrasButton)
												.addComponent(salirButton))
								.addContainerGap()));

		pack();
		setLocationRelativeTo(null);
	}

	private void animalButtonActionPerformed(java.awt.event.ActionEvent evt) {
		PopUpWindow hola = new PopUpWindow(this, rootPaneCheckingEnabled);
		String textoLabel;

		textoLabel = "¿Desea agregar a " + nombreText.getText().toString()
				+ " a BUSCAMASCOTAS?";

		hola.setLabelPopup(textoLabel);
		hola.setVisible(true);
		if (hola.getReturnStatus() == 1) {
			sacarString();
			System.out.println(getSql());
			ins.insertar(getSql());
			crearCarpetas();

			ins.desconectar();
		}
	}

	private void principalButtonActionPerformed(java.awt.event.ActionEvent evt) {
		MenuPrincipal.main();
		this.setVisible(false);
	}

	private void atrasButtonActionPerformed(java.awt.event.ActionEvent evt) {
		InsertarCliente.main();
		this.setVisible(false);
	}

	private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {
		int eleccion = JOptionPane.showConfirmDialog(null, "Desea salir?");

		if (eleccion == 0) {
			JOptionPane.showMessageDialog(null, "Saliendo del sistema");
			System.exit(0);
		}
	}

	public void salir() {
		setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent we) {

				int devolucion = JOptionPane.showConfirmDialog(null,
						"¿ESTA USTED SEGURO DE QUE DESEA SALIR?");
				if (devolucion == 0) {
					// TODO agregar subida de datos a dropbox. COPIA DE
					// SEGURIDAD.
					System.exit(0);
				}

			}
		});
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main() {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(InsertarAnimal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(InsertarAnimal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(InsertarAnimal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(InsertarAnimal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new InsertarAnimal().setVisible(true);
			}
		});
	}

	//Declaración de variables
	private javax.swing.JButton animalButton;
	private javax.swing.JButton atrasButton;
	private javax.swing.JLabel capaLabel;
	private javax.swing.JTextField capaText;
	private javax.swing.JLabel dietaLabel;
	private javax.swing.JTextField dietaText;
	private javax.swing.JLabel especieLabel;
	private javax.swing.JTextField especieText;
	private javax.swing.JLabel esterilizadoLabel;
	private javax.swing.JLabel esterilizadoLabel1;
	private javax.swing.JTextField esterilizadoText;
	private javax.swing.JTextField fechaMicroText;
	private javax.swing.JLabel fechachipLabel;
	private javax.swing.JTextField habitatText;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel microchipLabel;
	private javax.swing.JTextField microchipText;
	private javax.swing.JLabel nacimientoLabel;
	private javax.swing.JTextField nacimientoText;
	private javax.swing.JLabel nombreLabel;
	private javax.swing.JTextField nombreText;
	private javax.swing.JLabel peloLabel;
	private javax.swing.JTextField peloText;
	private javax.swing.JButton principalButton;
	private javax.swing.JLabel razaLabel;
	private javax.swing.JTextField razaText;
	private javax.swing.JButton salirButton;
	private javax.swing.JLabel sexoLabel;
	private javax.swing.JTextField sexoText;


//	private void calcularCarpeta() {
//		System.out.println(getSql());
//		boolean compIns = ins.insertar("SELECT last_insert_rowid()");
//		if (compIns == true) {
//			System.out.println("transaccion existosa!!");
//		} else {
//			System.out.println("error en la transaccion!!");
//		}
//	}

	private void sacarString() {

		nombre = nombreText.getText();
		String microchip = microchipText.getText();
		String fecha_chip = fechaMicroText.getText();
		String sexo = sexoText.getText();
		raza = razaText.getText();
		especie = especieText.getText();
		String tipo_pelo = peloText.getText();
		String capa = capaText.getText();
		String dieta = dietaText.getText();
		String habitat = habitatText.getText();
		String fecha_nacimiento = nacimientoText.getText();
		String esterilizado = esterilizadoText.getText();
		carpeta = nombre + ins.calcularCarpeta();

		setSql("insert into animales(NOM_ANIMAL,MICROCHIP,FECHA_CHIP,SEXO,ESPECIE,RAZA,TIPO_PELO,CAPA,"
				+ "DIETA,HABITAT,FECHA_NACIMIENTO,ESTERILIZADO,ID_CLIENTE,CARPETA) VALUES "
				+ "('"
				+ nombre
				+ "','"
				+ microchip
				+ "','"
				+ fecha_chip
				+ "','"
				+ sexo
				+ "',"
				+ "'"
				+ especie
				+ "','"
				+ raza
				+ "','"
				+ tipo_pelo
				+ "','"
				+ capa
				+ "','"
				+ dieta
				+ "',"
				+ "'"
				+ habitat
				+ "','"
				+ fecha_nacimiento
				+ "','"
				+ esterilizado
				+ "',"
				+ "'"
				+ InsertarCliente.getDNI()
				+ "', '"
				+ carpeta
				+ "')");

	}

	public void crearCarpetas() {

		ruta = System.getProperty("user.dir");

		String separador = System.getProperty("file.separator");
		String especieUPPER = especie.toUpperCase();
		String rutaCarpetaEspecie = ruta + separador + especieUPPER;

		File folderEspecie = new File(rutaCarpetaEspecie);

		@SuppressWarnings("unused")
		boolean createFolder = false;

		if (!folderEspecie.exists()) {
			createFolder = folderEspecie.mkdirs();
		}
		if (folderEspecie.exists()) {
			createFolder = false;

			String razaUPPER = raza.toUpperCase();
			String rutaCarpetaRaza = rutaCarpetaEspecie + separador + razaUPPER;
			File folderRaza = new File(rutaCarpetaRaza);

			if (!folderRaza.exists()) {
				createFolder = folderRaza.mkdirs();
			}
			if (folderRaza.exists()) {
				createFolder = false;
				String nombreUPPER = carpeta.toUpperCase();
				String rutaCarpetaNombre = rutaCarpetaRaza + separador
						+ nombreUPPER;
				File folderNombre = new File(rutaCarpetaNombre);
				if (!folderNombre.exists()) {
					createFolder = folderNombre.mkdirs();
				}
			}
		}
	}

}
