/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package buscamascotas.IU;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Alberto
 */
public class MenuPrincipal extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form MenuPrincipal
	 */
	public MenuPrincipal() {
		initComponents();

		salir();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {

		insertarButton = new javax.swing.JButton();
		buscarButton = new javax.swing.JButton();
		salirButton = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		insertarButton.setText("INSERTAR CLIENTE");
		insertarButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				insertarButtonActionPerformed(evt);
			}
		});

		buscarButton.setText("BUSCAR");
		buscarButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buscarButtonActionPerformed(evt);
			}
		});

		salirButton.setText("SALIR");
		salirButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				salirButtonActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36));
		jLabel1.setText("BUSCAMASCOTAS");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGap(0,
																		0,
																		Short.MAX_VALUE)
																.addComponent(
																		salirButton))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addGap(0,
																		0,
																		Short.MAX_VALUE)))
								.addContainerGap())
				.addGroup(
						layout.createSequentialGroup()
								.addGap(50, 50, 50)
								.addComponent(insertarButton)
								.addGap(71, 71, 71)
								.addComponent(buscarButton)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addGap(94, 94, 94)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(insertarButton)
												.addComponent(buscarButton))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										95, Short.MAX_VALUE)
								.addComponent(salirButton).addContainerGap()));

		pack();
		setLocationRelativeTo(null);
	}

	/**
	 * Al pulsar en INSERTAR nos lleva a la ventana InsertarCliente
	 * 
	 * @param evt
	 */
	private void insertarButtonActionPerformed(java.awt.event.ActionEvent evt) {
		InsertarCliente.main();
		this.setVisible(false);
	}

	/**
	 * Al pulsar en BUSCAR nos lleva a la ventana Buscar
	 * 
	 * @param evt
	 */
	private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {
		Buscar.main();
		this.setVisible(false);
	}

	/**
	 * Si se pulsa salir, salta un confirmdialog.
	 * 	Si seleccionas SI sales del sistema
	 * 	Si seleccinas NO, te mantienes en el.
	 * 
	 * @param evt
	 */
	private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {
		int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea salir?");

		if (eleccion == 0) {
			JOptionPane.showMessageDialog(null, "saliendo del sistema");
			System.exit(0);
		}
	}

	/**
	 * Si se pulsa la X, salta un confirmdialog.
	 * 	Si seleccionas SI sales del sistema
	 * 	Si seleccinas NO, te mantienes en el.
	 * 
	 * @param evt
	 */
	public void salir() {
		setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent we) {

				int devolucion = JOptionPane.showConfirmDialog(null,
						"¿ESTA USTED SEGURO DE QUE DESEA SALIR?");
//				System.out.println("dev: " + devolucion);
				if (devolucion == 0) {
					// TODO agregar subida de datos a dropbox. COPIA DE
					// SEGURIDAD.
					System.exit(0);
				}

			}
		});
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main() {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MenuPrincipal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MenuPrincipal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MenuPrincipal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MenuPrincipal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MenuPrincipal().setVisible(true);
			}
		});
	}

	// Declaracion de variables
	private javax.swing.JButton buscarButton;
	private javax.swing.JButton insertarButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JButton salirButton;
}
