package buscamascotas.IU;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Alberto
 */
public class PantallaInicial extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form InsertarCliente
	 */
	public PantallaInicial() {
		initComponents();
		userText.addKeyListener(new KeyListener() {

			@Override
			public void keyTyped(KeyEvent e) {
			}

			@Override
			public void keyPressed(KeyEvent e) {
				if (e.getKeyCode() == KeyEvent.VK_ENTER) {
					entrarActionPerformed(null);
				}
			}

			@Override
			public void keyReleased(KeyEvent e) {
			}
		});
		userPass.addKeyListener(new KeyListener() {

			@Override
			public void keyTyped(KeyEvent e) {
			}

			@Override
			public void keyPressed(KeyEvent e) {
				if (e.getKeyCode() == KeyEvent.VK_ENTER) {
					entrarActionPerformed(null);
				}
			}

			@Override
			public void keyReleased(KeyEvent e) {
			}
		});
		salir();
	}

	public void salir() {

		setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent we) {

				int devolucion = JOptionPane.showConfirmDialog(null,
						"¿ESTA USTED SEGURO DE QUE DESEA SALIR?");
				if (devolucion == 0) {
					// TODO agregar subida de datos a dropbox. COPIA DE
					// SEGURIDAD.
					System.exit(0);
				}

			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		entrar = new javax.swing.JButton();
		salir = new javax.swing.JButton();
		userPass = new javax.swing.JPasswordField();
		passLabel = new javax.swing.JLabel();
		userText = new javax.swing.JTextField();
		userLabel = new javax.swing.JLabel();
		error = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMaximumSize(new java.awt.Dimension(400, 300));
		setMinimumSize(new java.awt.Dimension(400, 300));
		setResizable(false);

		entrar.setText("ENTRAR");
		entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		entrar.setSelected(true);
		entrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				entrarActionPerformed(evt);
			}
		});

		salir.setText("SALIR");
		salir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				salirActionPerformed(evt);
			}
		});

		passLabel.setText("CONTRASEÑA");

		userText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				userTextActionPerformed(evt);
			}
		});

		userLabel.setText("USUARIO");

		jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); 
		jLabel1.setText("BUSCAMASCOTAS");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(91, 91, 91)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						passLabel)
																				.addComponent(
																						userLabel))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						userText,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						83,
																						Short.MAX_VALUE)
																				.addComponent(
																						userPass)))
												.addComponent(
														error,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														216,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		entrar)
																.addGap(26, 26,
																		26)
																.addComponent(
																		salir)
																.addGap(34, 34,
																		34))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addContainerGap()))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										67, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														userText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(userLabel))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														userPass,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(passLabel))
								.addGap(18, 18, 18)
								.addComponent(error,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										42,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(entrar)
												.addComponent(salir))
								.addGap(27, 27, 27)));

		pack();
		setLocationRelativeTo(null);
	}

	// TODO CREO QUE ESTO SOBRA
	private void userTextActionPerformed(java.awt.event.ActionEvent evt) {
	}// GEN-LAST:event_userTextActionPerformed

	/**
	 * Registra que se pulsa ENTRAR y comprueba user y pass correctos
	 * 	Si es correcto salta a MenuPrincipal
	 * 	Si no es correcto salta un mensaje de error.
	 * @param evt
	 */
	private void entrarActionPerformed(java.awt.event.ActionEvent evt) {
		String user = userText.getText();
		@SuppressWarnings("deprecation")
		String pass = userPass.getText();
		// TODO CAMBIAR por acceder a base de datos a comprobar usuario y contraseña
		if ((user.equals("sandra")) && (pass.equals("1234"))) {
			MenuPrincipal.main();
			setVisible(false);
		} else {
			error.setText("¡Usuario o contraseña incorrectos!");
		}
	}
	
	/**
	 * Si se pulsa la X, salta un confirmdialog.
	 * 	Si seleccionas SI sales del sistema
	 * 	Si seleccinas NO, te mantienes en el.
	 * 
	 * @param evt
	 */
	private void salirActionPerformed(java.awt.event.ActionEvent evt) {

		int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea salir?");

		if (eleccion == 0) {
			JOptionPane.showMessageDialog(null, "Saliendo del sistema");
			System.exit(0);
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PantallaInicial.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PantallaInicial.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PantallaInicial.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PantallaInicial.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PantallaInicial().setVisible(true);
			}
		});
	}

	//Declaración de variables
	private javax.swing.JButton entrar;
	private javax.swing.JLabel error;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel passLabel;
	private javax.swing.JButton salir;
	private javax.swing.JLabel userLabel;
	private javax.swing.JPasswordField userPass;
	private javax.swing.JTextField userText;
}
